POS_DICT = {
    'ADJ': 0,
    'ADP': 1,
    'ADV': 2,
    'AUX': 3,
    'CCONJ': 4,
    'DET': 5,
    'INTJ': 6,
    'NOUN': 7,
    'NUM': 8,
    'PART': 9,
    'PRON': 10,
    'PROPN': 11,
    'PUNCT': 12,
    'SCONJ': 13,
    'SYM': 14,
    'VERB': 15,
    'X': 16,
    '_': 17
}

RELS_DICT = {
    'acl': 0,
    'acl:attrib': 1,
    'acl:relcl': 2,
    'advcl': 3,
    'advmod': 4,
    'advmod:arg': 5,
    'amod': 6,
    'appos': 7,
    'aux': 8,
    'aux:aglt': 9,
    'aux:mood': 10,
    'aux:pass': 11,
    'case': 12,
    'cc': 13,
    'cc:preconj': 14,
    'ccomp': 15,
    'ccomp:obj': 16,
    'compound': 17,
    'compound:aglt': 18,
    'compound:cnd': 19,
    'compound:imp': 20,
    'conj': 21,
    'cop': 22,
    'cop:locat': 23,
    'csubj': 24,
    'dep': 25,
    'det': 26,
    'det:numgov': 27,
    'det:nummod': 28,
    'discourse': 29,
    'discourse:comment': 30,
    'discourse:emo': 31,
    'discourse:intj': 32,
    'expl:impers': 33,
    'expl:pv': 34,
    'fixed': 35,
    'flat': 36,
    'goeswith': 37,
    'iobj': 38,
    'list': 39,
    'mark': 40,
    'nmod': 41,
    'nmod:arg': 42,
    'nmod:poss': 43,
    'nmod:subj': 44,
    'nmod:title': 45,
    'nsubj': 46,
    'nsubj:pass': 47,
    'nummod': 48,
    'obj': 49,
    'obl': 50,
    'obl:agent': 51,
    'obl:arg': 52,
    'obl:comp': 53,
    'obl:pass': 54,
    'orphan': 55,
    'parataxis': 56,
    'punct': 57,
    'reparandum': 58,
    'root': 59,
    'vocative': 60,
    'xcomp': 61,
    'xcomp:obj': 62,
    '_': 63
}

RELS_LIST = ['acl',
             'acl:attrib',
             'acl:relcl',
             'advcl',
             'advmod',
             'advmod:arg',
             'amod',
             'appos',
             'aux',
             'aux:aglt',
             'aux:mood',
             'aux:pass',
             'case',
             'cc',
             'cc:preconj',
             'ccomp',
             'ccomp:obj',
             'compound',
             'compound:aglt',
             'compound:cnd',
             'compound:imp',
             'conj',
             'cop',
             'cop:locat',
             'csubj',
             'dep',
             'det',
             'det:numgov',
             'det:nummod',
             'discourse',
             'discourse:comment',
             'discourse:emo',
             'discourse:intj',
             'expl:impers',
             'expl:pv',
             'fixed',
             'flat',
             'goeswith',
             'iobj',
             'list',
             'mark',
             'nmod',
             'nmod:arg',
             'nmod:poss',
             'nmod:subj',
             'nmod:title',
             'nsubj',
             'nsubj:pass',
             'nummod',
             'obj',
             'obl',
             'obl:agent',
             'obl:arg',
             'obl:comp',
             'obl:pass',
             'orphan',
             'parataxis',
             'punct',
             'reparandum',
             'root',
             'vocative',
             'xcomp',
             'xcomp:obj',
             '_'
             ]
